apiVersion: 1

datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus-src
      access: proxy
      url: http://prometheus:9090
      jsonData:
        graphiteVersion: "1.1"
        tlsAuth: false
        tlsAuthWithCACert: false
      secureJsonData:
        tlsCACert: "..."
        tlsClientCert: "..."
        tlsClientKey: "..."
